services:
  nextapp:
      container_name: nextapp
      image: cappuchinosoft/flottajelenlet
      build:
        dockerfile: next.dockerfile
      ports:
        - 23000:3000
      environment:
        - NEXT_PUBLIC_API_URL=http://localhost:8080
        - FACEBOOK_CLIENT_ID=673328878328850
        - FACEBOOK_CLIENT_SECRET=7b55b25cefad0b238e8b16d1ea3e1d08
        - NEXTAUTH_SECRET=a_flotta_nyeri_a_bajnoksagot
      depends_on:
        - db
  db:
    container_name: db
    image: mysql:8.2
    environment:
      MYSQL_DATABASE: 'flotta'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'admin'
      # You can use whatever password you like
      MYSQL_PASSWORD: '10825660'
      # Password for root access
      MYSQL_ROOT_PASSWORD: '10825660'
    ports:
      - 23306:3306
    expose:
      # Opens port 3306 on the container
      - '23306'
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db: {}