services:
  # backend:
  #     container_name: backend
  #     image: cappuchinost/jelenletbackend
  #     build:
  #       context: "./backend"
  #       dockerfile: "go.dockerfile"
  #     ports:
  #       - 21323:1323
  #     extra_hosts:
  #       - "38.242.211.248:38.242.211.248"
  nextapp:
      container_name: nextapp
      image: cappuchinosoft/flottajelenlet
      build:
        dockerfile: next.dockerfile
      ports:
        - 23000:3000
      restart: always
  db:
    container_name: db
    image: mysql:8.2
    environment:
      MYSQL_DATABASE: 'flotta'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'admin'
      # You can use whatever password you like
      MYSQL_PASSWORD: '10825660'
      # Password for root access
      MYSQL_ROOT_PASSWORD: '10825660'
      TZ: Europe/Budapest 
    ports:
      - 23306:3306
    expose:
      # Opens port 3306 on the container
      - '23306'
    volumes:
      - my-db:/var/lib/mysql
    restart: always

volumes:
  my-db: {}